export const diseases = [
  {
    id: 'avian-influenza',
    name: 'Avian Influenza',
    causative_agent: 'Influenza A virus (subtypes H5N1, H5N8, H7N9)',
    affected_species: 'All poultry — chickens, turkeys, ducks, geese',
    overview:
      'Avian Influenza (AI), commonly called "bird flu", is a highly contagious viral disease affecting the respiratory, digestive, and nervous systems of birds. Highly Pathogenic Avian Influenza (HPAI) strains cause near 100% mortality in affected flocks within 48 hours. In Nigeria, HPAI outbreaks have caused catastrophic losses, particularly in the North during Harmattan season when wild migratory birds carry the virus across the Sahara.',
    key_signs: [
      'Sudden, unexplained mass mortality (>50% of flock in 24–48 hours)',
      'Swollen and haemorrhagic head, face, comb, and wattles',
      'Blue discolouration (cyanosis) of unfeathered skin',
      'Nasal discharge, coughing, sneezing, laboured breathing',
      'Watery green or white diarrhoea',
      'Twisted neck, loss of coordination (neurological signs)',
      'Sharp drop in egg production and soft-shelled eggs',
    ],
    at_risk_conditions: [
      { factor: 'Wild bird proximity (migratory waterfowl)', risk_level: 'Critical' },
      { factor: 'Harmattan season (Nov–Feb)', risk_level: 'Critical' },
      { factor: 'Open-sided housing', risk_level: 'High' },
      { factor: 'Nearby confirmed outbreak within 30km', risk_level: 'Critical' },
      { factor: 'Shared water sources with wild birds', risk_level: 'High' },
      { factor: 'Northern Nigeria (Kano, Kaduna, Sokoto belts)', risk_level: 'High' },
    ],
    prevention: [
      'Restrict wild bird access — net all ventilation openings and water points',
      'Implement strict biosecurity: footbaths, change of clothing before entering farm',
      'Source birds and hatching eggs only from certified disease-free hatcheries',
      'Register farm with the state veterinary authority for early warning alerts',
      'Vaccinate with approved AI vaccine under veterinary supervision where outbreaks are active',
      'Avoid live bird markets or purchasing birds of unknown origin',
    ],
    treatment: [
      'No specific treatment for HPAI — stamping-out policy applies in Nigeria',
      'Notify the State Veterinary Services Department immediately',
      'Do not attempt to treat or move birds — contain and report',
      'Antiviral supportive care under strict vet supervision for LPAI strains',
    ],
    nigerian_relevance:
      'Nigeria has experienced multiple HPAI H5N1 and H5N8 outbreaks since 2006, with the most severe waves in 2015–2016 affecting over 4 million birds across 15 states. Northern states bordering Lake Chad and the Sahel corridor are highest risk due to migratory waterfowl flyways. The NAQS (Nigerian Agricultural Quarantine Service) and NVRI (National Veterinary Research Institute, Vom) provide surveillance and confirmatory testing.',
    vet_alert:
      'Any unexplained sudden mass mortality must be reported to your state vet within 24 hours. Avian Influenza is a notifiable disease in Nigeria. Do not dispose of dead birds — preserve samples in double-sealed bags and refrigerate.',
  },
  {
    id: 'newcastle-disease',
    name: 'Newcastle Disease',
    causative_agent: 'Avian Paramyxovirus type 1 (APMV-1 / NDV)',
    affected_species: 'Chickens most severely; also turkeys, pigeons, and wild birds',
    overview:
      'Newcastle Disease (ND) is the most economically important poultry disease in Nigeria. It is highly contagious and spreads rapidly through airborne droplets, contaminated feed and water, fomites, and human movement. The velogenic (viscerotropic) strain prevalent in West Africa causes near-total flock mortality in unvaccinated birds. Vaccination is the cornerstone of control, but many smallholder and commercial farms in Nigeria maintain inadequate vaccination schedules.',
    key_signs: [
      'Gasping, coughing, gurgling respiratory sounds',
      'Greenish watery diarrhoea',
      'Sudden drop in feed and water intake',
      'Twisted neck (torticollis), tremors, paralysis of wings and legs',
      'Oedema of the face and wattles',
      'Sharp drop in egg production; misshapen, soft eggs',
      'High mortality — up to 100% in unvaccinated flocks within 3–5 days',
    ],
    at_risk_conditions: [
      { factor: 'Unvaccinated flock or lapsed vaccination', risk_level: 'Critical' },
      { factor: 'Flock age 4–8 weeks (maternal antibody waning)', risk_level: 'High' },
      { factor: 'Wet season (high rainfall + humidity)', risk_level: 'High' },
      { factor: 'Free-range housing with bird traffic', risk_level: 'High' },
      { factor: 'Mixing birds of different ages or sources', risk_level: 'High' },
    ],
    prevention: [
      'Vaccinate at day-old with La Sota or HB1 strain by eye drop or drinking water',
      'Booster vaccination at 3–4 weeks, then every 8–12 weeks throughout production',
      'Maintain strict all-in all-out flock management',
      'Disinfect housing thoroughly between flocks',
      'Source birds only from certified disease-free hatcheries',
    ],
    treatment: [
      'No specific antiviral treatment for Newcastle Disease',
      'Supportive therapy: vitamins A, C, E in drinking water to boost immunity',
      'Antibiotic cover to prevent secondary bacterial infections (under vet guidance)',
      'Vaccinate remaining healthy birds immediately to limit spread',
      'Cull severely affected birds humanely',
    ],
    nigerian_relevance:
      'Newcastle Disease is endemic throughout Nigeria and is the leading cause of poultry mortality in backyard and semi-commercial flocks. The Veterinary Council of Nigeria recommends La Sota intraocular vaccination at day 1 and 21, with Komarov or inactivated oil emulsion boosters at 6–8 weeks. Annual losses to ND in Nigeria are estimated at ₦30–50 billion.',
    vet_alert:
      'If mortality exceeds 5% in a single day and birds show neurological signs, contact your vet immediately. Emergency vaccination of the remaining flock may reduce losses.',
  },
  {
    id: 'gumboro-disease',
    name: 'Infectious Bursal Disease (Gumboro)',
    causative_agent: 'Birnavirus (Infectious Bursal Disease Virus — IBDV)',
    affected_species: 'Chickens (broilers and layers), primarily 3–6 weeks of age',
    overview:
      'Gumboro Disease, named after the town in Delaware where it was first described, causes severe immunosuppression by destroying the Bursa of Fabricius — the primary lymphoid organ in young chickens. Birds that survive Gumboro become immunocompromised for life, making them susceptible to secondary infections and reducing vaccine efficacy. The disease causes significant economic losses in Nigerian commercial broiler operations.',
    key_signs: [
      'Sudden onset of depression and droopiness',
      'Whitish, watery diarrhoea with soiled vent feathers',
      'Trembling and unsteady gait',
      'Ruffled feathers, birds huddling together',
      'Birds pecking at their own cloacae',
      'Mortality peak at 3–5 days post-infection, then decline',
      'At post-mortem: enlarged, haemorrhagic, creamy Bursa of Fabricius',
    ],
    at_risk_conditions: [
      { factor: 'Age 3–6 weeks (peak susceptibility window)', risk_level: 'Critical' },
      { factor: 'Unvaccinated or under-vaccinated flock', risk_level: 'Critical' },
      { factor: 'High stocking density (>25 birds/m²)', risk_level: 'High' },
      { factor: 'Variant/very virulent IBDV strains (vvIBDV)', risk_level: 'High' },
      { factor: 'Previous farm history of Gumboro', risk_level: 'High' },
    ],
    prevention: [
      'Vaccinate with live IBDV vaccine (intermediate or intermediate-plus strain) at days 10–14',
      'Booster at day 21 where very virulent strains are present',
      'Thoroughly clean and disinfect houses between flocks — IBDV survives in environment for months',
      'Avoid introducing birds from unknown sources',
      'Use in-ovo or day-old vaccination programs in high-risk areas',
    ],
    treatment: [
      'No specific antiviral treatment',
      'Supportive care: oral electrolytes (ORS) in drinking water',
      'Vitamins A, B-complex, and C to support recovery',
      'Reduce stress: lower stocking density, ensure comfortable temperatures',
      'Antibiotic therapy under vet guidance to prevent secondary infections',
    ],
    nigerian_relevance:
      'Gumboro Disease is endemic in Nigerian commercial broiler farms. Very virulent IBDV strains (vvIBDV) circulate in many states and require more potent intermediate-plus vaccines. Farm-level mortality of 20–40% is common in unvaccinated flocks. The NVRI Vom produces locally adapted Gumboro vaccines suited to Nigerian IBDV strains.',
    vet_alert:
      'Call your vet if you observe sudden increase in mortality in broilers aged 3–6 weeks alongside characteristic diarrhoea and Bursa lesions at post-mortem. Early diagnosis allows rapid implementation of biosecurity to contain spread.',
  },
  {
    id: 'mareks-disease',
    name: "Marek's Disease",
    causative_agent: 'Marek\'s Disease Virus (MDV) — Herpesvirus of Turkeys (HVT) group',
    affected_species: 'Chickens, primarily 12–30 weeks; turkeys occasionally',
    overview:
      "Marek's Disease is a lymphoproliferative disease caused by a highly cell-associated herpesvirus. The virus spreads through feather follicle dander and dust, making it extremely contagious. It causes tumours in peripheral nerves, visceral organs, and the eye. While vaccination at hatch effectively prevents clinical disease, the virus persists in vaccinated flocks and continues circulating in the environment.",
    key_signs: [
      'Progressive leg or wing paralysis (birds cannot stand)',
      '"Floppy chicken" posture — one leg stretched forward, one backward',
      'Grey discolouration of the iris (grey eye / ocular Marek\'s)',
      'Tumours in liver, spleen, kidney, gonads (visceral form)',
      'Skin thickening and feather follicle tumours',
      'Sudden death in apparently healthy birds (acute form)',
      'Stunted growth and immunosuppression in young flocks',
    ],
    at_risk_conditions: [
      { factor: 'Unvaccinated at hatch or vaccine cold-chain failure', risk_level: 'Critical' },
      { factor: 'Age 12–25 weeks (peak clinical onset)', risk_level: 'High' },
      { factor: 'Contaminated litter or house environment', risk_level: 'High' },
      { factor: 'Introduction of new birds into endemic farm', risk_level: 'High' },
    ],
    prevention: [
      'Vaccinate all chicks at hatch (day 0) with HVT vaccine — this is the critical window',
      'Ensure strict cold-chain for vaccine storage (2–8°C, never frozen)',
      'Use combined HVT + SB-1 or Rispens vaccines in high-challenge environments',
      'Maintain biosecurity to prevent introduction of infected birds',
      'Source day-old chicks only from MDV-vaccinated breeder flocks',
    ],
    treatment: [
      'No treatment once clinical signs appear',
      'Cull affected birds to reduce suffering and prevent spread',
      'Investigate vaccination history and cold chain to prevent recurrence',
      'Consult veterinarian for post-mortem confirmation',
    ],
    nigerian_relevance:
      "Marek's Disease is widespread in Nigerian layer and broiler farms. Lapses in cold-chain management during vaccination distribution are a leading cause of vaccine failure. Commercial hatcheries in Lagos, Ogun, and Oyo states have adopted automated spray vaccination systems to ensure dose consistency.",
    vet_alert:
      'Contact your vet if you observe progressive paralysis in growing birds (12–30 weeks). Post-mortem examination of affected birds is important to differentiate from Lymphoid Leukosis, which has similar clinical presentation.',
  },
  {
    id: 'infectious-bronchitis',
    name: 'Infectious Bronchitis',
    causative_agent: 'Infectious Bronchitis Virus (IBV) — Gammacoronavirus',
    affected_species: 'Chickens of all ages; young birds most severely affected',
    overview:
      'Infectious Bronchitis (IB) is a highly contagious respiratory disease caused by a coronavirus that mutates rapidly, producing numerous serotypes. IB spreads through the air, contaminated equipment, and personnel. In layers, it causes significant drops in egg production and quality. IBV can also target the kidneys (nephropathogenic strains), causing acute mortality in young birds.',
    key_signs: [
      'Sudden onset of coughing, sneezing, and nasal discharge',
      'Gasping and rattling sounds (especially at night)',
      'Watery eyes (conjunctivitis)',
      'Drop in egg production (up to 50%) in laying hens',
      'Misshapen, soft-shelled, rough-textured, or watery albumen eggs',
      'In young chicks: severe respiratory distress and mortality',
      'Kidney form: increased water intake, wet litter, white urate deposits in kidneys',
    ],
    at_risk_conditions: [
      { factor: 'Cold temperatures below 22°C with high humidity', risk_level: 'High' },
      { factor: 'Chicks under 3 weeks old', risk_level: 'High' },
      { factor: 'Poor ventilation / inadequate air exchange', risk_level: 'High' },
      { factor: 'Overcrowded housing', risk_level: 'Medium' },
      { factor: 'Unvaccinated or single-strain vaccinated flock', risk_level: 'High' },
    ],
    prevention: [
      'Vaccinate at day 1 (H120 or Ma5 strain) and booster at 3–4 weeks',
      'Use multivalent IB vaccines or 4/91 strain to cover multiple serotypes',
      'Maintain house temperature above 22°C for chicks in first 2 weeks',
      'Ensure adequate ventilation without cold draughts',
      'All-in all-out management to break transmission cycles',
    ],
    treatment: [
      'No specific antiviral treatment for IBV',
      'Increase house temperature by 2–3°C to support recovery',
      'Electrolytes and vitamin supplements in drinking water',
      'Broad-spectrum antibiotics (under vet guidance) for secondary bacterial infections',
      'For kidney form: flush kidneys with increased water intake and ammonium chloride',
    ],
    nigerian_relevance:
      'Infectious Bronchitis is increasingly important in Nigerian layer operations, where multiple IBV serotypes including the 793/B (4/91) variant have been identified. Harmattan dry-cold conditions in Northern Nigeria create an annual peak season for IB between November and February.',
    vet_alert:
      'Call your vet if respiratory signs are accompanied by a sudden drop in egg production or you observe misshapen eggs. Differentiate from Newcastle Disease — IB does not typically cause neurological signs.',
  },
  {
    id: 'fowl-typhoid',
    name: 'Fowl Typhoid',
    causative_agent: 'Salmonella gallinarum (host-specific, non-motile)',
    affected_species: 'Chickens and turkeys of all ages; adults more commonly affected',
    overview:
      'Fowl Typhoid is a severe systemic bacterial infection caused by Salmonella gallinarum. Unlike Salmonella Enteritidis, this strain is host-specific and does not typically infect humans. It causes high mortality in adult birds and spreads rapidly through contaminated feed, water, and fomites. The disease is often introduced through infected replacement stock or contaminated day-old chicks.',
    key_signs: [
      'Sudden increased mortality in adult birds',
      'Pale, shrunken combs and wattles (anaemia)',
      'Bright yellow-green diarrhoea',
      'Lethargy, droopiness, and reluctance to move',
      'Increased thirst and reduced feed intake',
      'Drop in egg production in layers',
      'Post-mortem: bronze-coloured enlarged liver, swollen spleen and kidneys',
    ],
    at_risk_conditions: [
      { factor: 'High flock density with poor sanitation', risk_level: 'High' },
      { factor: 'Contaminated feed or water supply', risk_level: 'High' },
      { factor: 'Mortality rate above 5% with no vaccination history', risk_level: 'High' },
      { factor: 'Introduction of untested replacement pullets', risk_level: 'High' },
      { factor: 'Poor biosecurity — open farm access', risk_level: 'Medium' },
    ],
    prevention: [
      'Source replacement stock only from Salmonella-tested, certified flocks',
      'Vaccinate with 9R live attenuated Salmonella gallinarum vaccine',
      'Chlorinate water supply and monitor feed storage for contamination',
      'Implement strict rodent control — rats are reservoir hosts',
      'Maintain clean, dry litter and remove wet spots daily',
    ],
    treatment: [
      'Collect dead birds for post-mortem and bacterial culture before starting treatment',
      'Enrofloxacin, ampicillin, or sulphonamides — always under vet prescription',
      'Note: antibiotic resistance is increasing — culture and sensitivity testing recommended',
      'Sanitise all water drinkers and feed troughs immediately',
      'Cull clinically affected birds to reduce bacterial load',
    ],
    nigerian_relevance:
      'Fowl Typhoid is common in Nigerian layer and breeder farms. The absence of systematic Salmonella testing in hatcheries means contaminated stock is frequently introduced into clean farms. The 9R vaccine, produced by NVRI Vom, is available and cost-effective for commercial layer operations.',
    vet_alert:
      'Submit dead birds with intact organs to your state Animal Health laboratory for culture and antibiogram before starting antibiotics. Inappropriate antibiotic use without sensitivity data drives resistance and treatment failure.',
  },
  {
    id: 'coccidiosis',
    name: 'Coccidiosis',
    causative_agent: 'Eimeria spp. (E. tenella, E. acervulina, E. necatrix, E. brunetti)',
    affected_species: 'Chickens primarily; also turkeys and other poultry',
    overview:
      'Coccidiosis is a parasitic disease of the intestinal tract caused by intracellular protozoa of the genus Eimeria. It is one of the most economically costly diseases in commercial broiler production worldwide. Each Eimeria species targets a different part of the intestine. The parasite spreads through oocysts shed in droppings and activated by warm, moist conditions — making wet seasons in Nigeria a peak risk period. Subclinical coccidiosis (no visible signs, but impaired growth) is far more common and costly than the clinical form.',
    key_signs: [
      'Bloody diarrhoea (E. tenella — caecal form, most acute)',
      'Loose, mucoid, or watery droppings (other Eimeria species)',
      'Droopiness, ruffled feathers, huddling near heat source',
      'Reduced feed intake and sudden drop in weight gain',
      'Pale mucous membranes (anaemia in severe cases)',
      'High mortality in chicks 3–8 weeks old with no prior immunity',
      'Wet, caked litter with high ammonia odour',
    ],
    at_risk_conditions: [
      { factor: 'Humidity above 80% with wet/compacted litter', risk_level: 'High' },
      { factor: 'Open-sided housing during rainy season', risk_level: 'High' },
      { factor: 'High stocking density with poor litter management', risk_level: 'High' },
      { factor: 'No anticoccidial in feed programme', risk_level: 'High' },
      { factor: 'Birds aged 3–8 weeks (peak susceptibility)', risk_level: 'High' },
    ],
    prevention: [
      'Include anticoccidials (amprolium, salinomycin, monensin, or diclazuril) in starter/grower feed',
      'Maintain dry litter — remove wet patches immediately, never allow caking',
      'Control drinker spillage — the leading cause of wet litter',
      'Vaccinate broilers with live oocyst vaccine (Paracox or Hipracox) as an alternative to anticoccidials',
      'Rotate anticoccidial classes to prevent resistance',
    ],
    treatment: [
      'Amprolium in drinking water for 5–7 days (20mg/kg body weight)',
      'Toltrazuril (Baycox) single dose — highly effective against all Eimeria species',
      'Diclazuril as an alternative to toltrazuril',
      'Vitamin K supplementation to address intestinal bleeding',
      'Improve litter management immediately alongside treatment',
    ],
    nigerian_relevance:
      'Coccidiosis is the second most common cause of broiler mortality in Nigeria after Newcastle Disease. The wet season (August–October) sees a dramatic increase in clinical cases, particularly in South-West and South-South Nigeria where humidity consistently exceeds 80%. Many small-scale farmers in Nigeria do not include anticoccidial premixes in feed formulations due to cost, significantly increasing farm risk.',
    vet_alert:
      'Bloody diarrhoea in chicks aged 3–6 weeks is a veterinary emergency. E. tenella caecal coccidiosis can kill 50% of a flock within 24–48 hours without treatment. Call your vet immediately if you observe blood in droppings.',
  },
  {
    id: 'heat-stress',
    name: 'Heat Stress Syndrome',
    causative_agent: 'Environmental — sustained high temperature combined with high humidity',
    affected_species: 'All poultry, especially broilers and high-production layers',
    overview:
      "Heat Stress Syndrome occurs when a bird's internal thermoregulatory mechanisms are overwhelmed by environmental heat load. Poultry have no sweat glands and rely on panting (evaporative cooling through the respiratory tract) to dissipate heat. When ambient temperature exceeds 32°C and humidity is high, this mechanism becomes insufficient. Heat stress causes immunosuppression, reduced growth rates, decreased egg production, eggshell quality deterioration, and death. Nigeria's long hot seasons make this one of the most pervasive and consistently costly conditions in commercial poultry production.",
    key_signs: [
      'Rapid open-beak panting (tachypnoea)',
      'Outstretched wings held away from body',
      'Reduced movement and lethargy',
      'Increased water intake, reduced feed consumption',
      'Pale combs and wattles',
      'Drop in egg production and thin-shelled or shell-less eggs',
      'Sudden death in severe cases (especially in closed houses)',
    ],
    at_risk_conditions: [
      { factor: 'Temperature above 32°C with humidity above 70%', risk_level: 'Critical' },
      { factor: 'Closed housing with inadequate ventilation', risk_level: 'High' },
      { factor: 'High stocking density', risk_level: 'High' },
      { factor: 'Wet season afternoon hours (2pm–5pm)', risk_level: 'High' },
      { factor: 'Broilers at 4–7 weeks (high metabolic heat output)', risk_level: 'High' },
    ],
    prevention: [
      'Install tunnel ventilation fans or evaporative cooling pads in closed houses',
      'Reduce stocking density by 10–15% during peak hot months',
      'Feed during the coolest parts of the day (early morning 5–8am, evening 6–8pm)',
      'Ensure cool, fresh water is always available — clean drinkers every 2 hours in extreme heat',
      'Install shade netting on south and west-facing walls for open-sided houses',
      'Plant trees or use white reflective roofing to reduce radiant heat load',
    ],
    treatment: [
      'Immediately open all ventilation panels and increase fan speed',
      'Provide ice-cold water or mist netting to rapidly cool the air',
      'Add sodium bicarbonate (1g/litre) and potassium chloride to drinking water to replace lost electrolytes',
      'Reduce feed allocation during peak heat — feed generates metabolic heat',
      'Vitamin C supplementation (200mg/litre water) reduces physiological stress',
    ],
    nigerian_relevance:
      'Heat Stress Syndrome is a year-round challenge in Southern Nigeria and a peak-season challenge (March–May) in the North. The combination of Nigeria\'s tropical climate with the enclosed, high-density nature of commercial broiler production creates optimal conditions for heat mortality events. Layer farms consistently report 15–25% drops in egg production during extreme heat periods.',
    vet_alert:
      "Call your vet if birds are dying in numbers during hot weather. Heat stroke is reversible in mild cases but progresses quickly. If house temperature exceeds 38°C, emergency cooling measures (wet burlap, ice water sprays) must begin within minutes.",
  },
  {
    id: 'fowl-pox',
    name: 'Fowl Pox',
    causative_agent: 'Avipoxvirus (Fowlpox virus)',
    affected_species: 'Chickens, turkeys, and a wide range of wild birds',
    overview:
      'Fowl Pox is a slow-spreading viral disease transmitted primarily by biting insects — particularly mosquitoes. It presents in two forms: the dry form (cutaneous) with wart-like lesions on unfeathered skin, and the wet form (diphtheritic) with caseous plaques in the mouth, throat, and trachea. The wet form is far more serious, causing suffocation and high mortality. The virus is robust in the environment and can survive for months in dried scabs.',
    key_signs: [
      'Dry form: wart-like nodular lesions on comb, wattles, eyelids, and face',
      'Lesions begin as small raised bumps, enlarge to dark brown scabs',
      'Wet form: yellowish-white plaques in mouth, tongue, and throat',
      'Gasping, difficulty swallowing (wet form)',
      'Reduced feed intake and weight loss',
      'Temporary drop in egg production',
      'Eye swelling and discharge (when pox lesions affect eyelids)',
    ],
    at_risk_conditions: [
      { factor: 'High mosquito activity (rainy season, stagnant water nearby)', risk_level: 'High' },
      { factor: 'Unvaccinated flock', risk_level: 'High' },
      { factor: 'Open-sided housing without insect netting', risk_level: 'Medium' },
      { factor: 'Injuries from feather pecking (skin entry points)', risk_level: 'Medium' },
      { factor: 'Introduction of carrier birds', risk_level: 'High' },
    ],
    prevention: [
      'Vaccinate with Fowl Pox live attenuated vaccine via wing-web stab method at 6–8 weeks',
      'Control mosquitoes: eliminate standing water, use insect netting on ventilation openings',
      'Apply approved insecticides or repellents around house perimeter',
      'Avoid overcrowding which causes feather-pecking injuries that serve as virus entry points',
      'Isolate newly introduced birds for 2–3 weeks before mixing with existing flock',
    ],
    treatment: [
      'No specific antiviral treatment for Fowl Pox',
      'Dry form: apply iodine solution or tincture to lesions to prevent secondary infection',
      'Wet form: carefully remove pseudomembrane plaques with forceps and apply iodine to lesions',
      'Broad-spectrum antibiotics under vet guidance for secondary bacterial infections',
      'Supportive care: soft feed or wet mash to ease swallowing in wet form cases',
    ],
    nigerian_relevance:
      'Fowl Pox is endemic throughout Nigeria and peaks during the late rainy season (September–November) when mosquito populations are at their highest. The disease is often underdiagnosed and conflated with other skin conditions. Wing-web vaccination with locally produced NVRI Fowl Pox vaccine provides solid, long-lasting immunity.',
    vet_alert:
      'Seek veterinary help immediately if birds show the wet (diphtheritic) form with mouth lesions — affected birds can suffocate rapidly. A vet should demonstrate removal technique to prevent further trauma to the respiratory tract.',
  },
]
